language: python
python:
  - "3.6"

script:
- python -m unittest
- coverage run --source=viroconcom  -m unittest
- cd docs/ && make clean && make html && touch _build/html/.nojekyll && cd ..

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/_build/html
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: issue#2-add-ci
